apiVersion: v1
kind: Pod
metadata:
  name: jmx-test
  annotations:
    ad.datadoghq.com/my-java-app.check_names: |
      [
        "jmx"
      ]
    ad.datadoghq.com/my-java-app.init_configs: |
      [
        {}
      ]
# Example ad.datadoghq.com/my-java-app.instances: |
# Port should always be specified if known
# jmx_url should be specified if it does not follow: service:jmx:rmi:///jndi/rmi://%%host%%:%%port%%/jmxrmi
#    ad.datadoghq.com/my-java-app.instances: |
#      [
#        {
#          "host": "%%host%%",
#          "port": "7199",
#          "jmx_url": "service:jmx:rmi:///jndi/rmi://%%host%%:7199/jmxrmi"
#        }
#      ]
    ad.datadoghq.com/my-java-app.instances: |
      [
        {
          "host": "%%host%%",
          "port": "%%port%%"
        }
      ]

    ad.datadoghq.com/my-java-app.logs: |
      [
        {
          "source":"java",
          "service":"my-java-app"
        }
      ]
  labels:
    name: my-java-app
spec:
  containers:
    - name: my-java-app
      image: dogdemo/my-java-app:latest
      ports:
        - containerPort: 7199
